"""Deterministic source signals used for selection order and audit only."""

from __future__ import annotations

import math
from datetime import datetime, timezone
from typing import Any, Mapping
from urllib.parse import urlparse

from .models import (
    COMMUNITY_SOCIAL,
    OFFICIAL_MODEL_COMPANY,
    PROJECT_TOOL,
    FetchItem,
    SourceSpec,
)
from .policies import (
    _coerce_item,
    _is_producthunt,
    item_datetime,
    matched_keywords,
    normalise_datetime,
    source_spec_from_config,
)


def score_item(
    item: FetchItem | Mapping[str, Any] | Any,
    source: SourceSpec | Mapping[str, Any] | Any | None = None,
    *,
    now: datetime | None = None,
) -> float:
    """Return a deterministic 0-100 selection signal.

    This value is never an AI score and is not a GitHub inclusion gate. GitHub
    rows are selected and displayed from their raw repository metrics in the
    policy/reader layers.
    """

    fetch_item = _coerce_item(item)
    current = normalise_datetime(now or datetime.now(timezone.utc))
    spec = _coerce_source_for_item(fetch_item, source)
    content_class = spec.content_class
    if content_class == OFFICIAL_MODEL_COMPANY:
        return _score_official(fetch_item, spec, current)
    if content_class == PROJECT_TOOL:
        return _score_project(fetch_item, spec, current)
    return _score_community(fetch_item, spec, current)


def score_breakdown(
    item: FetchItem | Mapping[str, Any] | Any,
    source: SourceSpec | Mapping[str, Any] | Any | None = None,
    *,
    now: datetime | None = None,
) -> dict[str, float]:
    """Return named components useful for diagnostics and tests.

    ``score_item`` remains the stable scalar API; this function exposes the
    same calculation without requiring callers to duplicate metric extraction.
    """

    fetch_item = _coerce_item(item)
    current = normalise_datetime(now or datetime.now(timezone.utc))
    spec = _coerce_source_for_item(fetch_item, source)
    if spec.content_class == OFFICIAL_MODEL_COMPANY:
        date = item_datetime(fetch_item, "published_at")
        age = _recency_fraction(date, current, _window(spec, 30))
        keywords = spec.selection_policy.keywords
        if not keywords:
            from .policies import DEFAULT_OFFICIAL_KEYWORDS

            keywords = DEFAULT_OFFICIAL_KEYWORDS
        keyword = 1.0 if matched_keywords(fetch_item, keywords) else 0.0
        link = 1.0 if _has_http_url(fetch_item.url) else 0.0
        return _components(age=age * 70, keywords=keyword * 20, link=link * 10)
    if spec.content_class == PROJECT_TOOL:
        if _is_producthunt(spec):
            votes = _log_metric(fetch_item.metrics, fetch_item.raw_payload, "votes", "vote_count", "upvotes", "points")
            date = item_datetime(fetch_item, "published_at")
            age = _recency_fraction(date, current, _window(spec, 30))
            comments = _log_metric(fetch_item.metrics, fetch_item.raw_payload, "comments", "comments_count")
            return _components(votes=votes * 55, recency=age * 35, comments=comments * 10)
        date = item_datetime(fetch_item, "published_at")
        return _components(recency=_recency_fraction(date, current, _window(spec, 30)) * 60, engagement=_engagement_fraction(fetch_item) * 30, link=float(_has_http_url(fetch_item.url)) * 10)

    date = item_datetime(fetch_item, "published_at")
    return _components(recency=_recency_fraction(date, current, _window(spec, 7)) * 55, engagement=_engagement_fraction(fetch_item) * 35, link=float(_has_http_url(fetch_item.url)) * 10)


def _score_official(item: FetchItem, source: SourceSpec, now: datetime) -> float:
    date = item_datetime(item, "published_at")
    age = _recency_fraction(date, now, _window(source, 30))
    keywords = source.selection_policy.keywords
    # A SourceSpec generated by the policy layer always carries defaults, but
    # retaining the fallback makes manually-created specs safe too.
    if not keywords:
        from .policies import DEFAULT_OFFICIAL_KEYWORDS

        keywords = DEFAULT_OFFICIAL_KEYWORDS
    keyword = 1.0 if matched_keywords(item, keywords) else 0.0
    link = 1.0 if _has_http_url(item.url) else 0.0
    return _clamp(age * 70 + keyword * 20 + link * 10)


def _score_project(item: FetchItem, source: SourceSpec, now: datetime) -> float:
    if _is_producthunt(source):
        votes = _log_metric(item.metrics, item.raw_payload, "votes", "vote_count", "upvotes", "points")
        date = item_datetime(item, "published_at")
        recency = _recency_fraction(date, now, _window(source, 30))
        comments = _log_metric(item.metrics, item.raw_payload, "comments", "comments_count")
        return _clamp(votes * 55 + recency * 35 + comments * 10)
    date = item_datetime(item, "published_at")
    return _clamp(_recency_fraction(date, now, _window(source, 30)) * 60 + _engagement_fraction(item) * 30 + float(_has_http_url(item.url)) * 10)


def _score_community(item: FetchItem, source: SourceSpec, now: datetime) -> float:
    date = item_datetime(item, "published_at")
    return _clamp(_recency_fraction(date, now, _window(source, 7)) * 55 + _engagement_fraction(item) * 35 + float(_has_http_url(item.url)) * 10)


def _coerce_source_for_item(item: FetchItem, source: Any | None) -> SourceSpec:
    if source is not None:
        return source_spec_from_config(source)
    return source_spec_from_config(
        {
            "id": item.source_id or "community_item",
            "name": item.source_id or "Community item",
            "type": "rss",
            "source_role": "community",
        }
    )


def _window(source: SourceSpec, fallback: int) -> int:
    return source.selection_policy.max_age_days or source.selection_policy.time_window_days or fallback


def _recency_fraction(value: datetime | None, now: datetime, window_days: int) -> float:
    if value is None:
        return 0.0
    current = normalise_datetime(now)
    timestamp = normalise_datetime(value)
    age_seconds = max(0.0, (current - timestamp).total_seconds())
    window_seconds = max(1.0, window_days * 86400.0)
    return max(0.0, min(1.0, 1.0 - age_seconds / window_seconds))


def _log_metric(
    metrics: Mapping[str, Any],
    raw_payload: Mapping[str, Any],
    *names: str,
) -> float:
    """Normalize one metric across the canonical and raw payload mappings."""

    value = 0.0
    for container in (metrics, raw_payload):
        for name in names:
            candidate = container.get(name)
            try:
                number = float(candidate)
            except (TypeError, ValueError):
                number = 0.0
            value = max(value, number)
    # Reference points keep scores comparable while preserving monotonicity.
    reference = 100_000.0
    return min(1.0, math.log1p(max(0.0, value)) / math.log1p(reference))


def _engagement_fraction(item: FetchItem) -> float:
    value = max(
            _number_from(
                item.metrics,
                "engagement",
                "likes",
                "reposts",
                "retweets",
                "replies",
                "votes",
                "upvotes",
                "comments",
                "comments_count",
                "num_comments",
                "score",
                "views",
                "view_count",
                "quote_count",
            ),
        _number_from(
            item.raw_payload,
            "engagement",
            "likes",
            "reposts",
            "retweets",
            "replies",
            "votes",
            "upvotes",
                "comments",
                "comments_count",
                "num_comments",
                "score",
                "views",
                "view_count",
                "quote_count",
            ),
    )
    return min(1.0, math.log1p(value) / math.log1p(10_000.0))


def _number_from(container: Mapping[str, Any], *names: str) -> float:
    result = 0.0
    for name in names:
        try:
            result = max(result, float(container.get(name) or 0))
        except (TypeError, ValueError):
            continue
    return max(0.0, result)


def _has_http_url(value: str | None) -> bool:
    if not value:
        return False
    parsed = urlparse(value)
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def _components(**values: float) -> dict[str, float]:
    return {key: round(float(value), 4) for key, value in values.items()}


def _clamp(value: float) -> float:
    return round(max(0.0, min(100.0, float(value))), 4)
