from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from dateutil import parser as date_parser


HOTLIST_FILENAME = "github_project_hotlist_cn.jsonl"
DEFAULT_REPORT_ROOT = Path("output")


@dataclass(frozen=True)
class GitHubHotspotFilters:
    query: str | None = None
    level: str | None = None
    language: str | None = None
    project_type: str | None = None
    min_score: int | None = None
    include_risky: bool = True


@dataclass(frozen=True)
class GitHubHotspotRow:
    normalized_item_id: int | None
    raw_item_id: int | None
    repo_full_name: str
    url: str | None
    homepage: str | None
    source_id: str | None
    published_at: datetime | None
    summary_cn: str | None
    description_cn: str | None
    project_type: str | None
    keywords: list[str]
    target_users: list[str]
    main_features: list[str]
    how_to_try: str | None
    stars: int
    forks: int
    watchers: int
    open_issues: int
    primary_language: str | None
    license_name: str | None
    pushed_at: datetime | None
    latest_release_names: list[str]
    final_score: int
    level: str
    decision: str
    ai_relevance_score: int
    popularity_score: int
    activity_score: int
    quality_score: int
    usability_score: int
    risk_score: int
    rank_reason: str | None
    risk_flags: list[str]

    @property
    def display_title(self) -> str:
        return self.repo_full_name or "unknown/repository"

    @property
    def is_risky(self) -> bool:
        return bool(self.risk_flags) or self.risk_score >= 40


@dataclass(frozen=True)
class GitHubHotspotStats:
    total: int
    strong_count: int
    hot_count: int
    watch_count: int
    risky_count: int
    report_path: Path | None
    updated_at: datetime | None


@dataclass(frozen=True)
class GitHubHotspotList:
    rows: list[GitHubHotspotRow]
    stats: GitHubHotspotStats


class GitHubHotspotReportReader:
    """Read GitHub project hotspot JSONL reports for the local web UI.

    The report is generated by github_project_report_job.  This reader keeps
    the web layer file-backed for the first UI iteration and intentionally
    ignores heavy README fields so pages stay fast.
    """

    def __init__(self, report_path: str | Path | None = None, *, output_root: str | Path = DEFAULT_REPORT_ROOT) -> None:
        self.report_path = Path(report_path) if report_path else None
        self.output_root = Path(output_root)

    def list_hotspots(
        self,
        *,
        filters: GitHubHotspotFilters | None = None,
        limit: int | None = None,
    ) -> GitHubHotspotList:
        filters = filters or GitHubHotspotFilters()
        report_path = self.resolve_report_path()
        if report_path is None:
            return GitHubHotspotList(rows=[], stats=self._stats([], None))

        rows = [row for row in self._read_rows(report_path) if _matches_filters(row, filters)]
        rows.sort(key=lambda row: (row.final_score, _datetime_sort_value(row.pushed_at)), reverse=True)
        stats = self._stats(rows, report_path)
        if limit is not None:
            rows = rows[: max(limit, 0)]
        return GitHubHotspotList(rows=rows, stats=stats)

    def search(self, query: str, *, limit: int = 8) -> list[GitHubHotspotRow]:
        normalized = query.strip()
        if not normalized:
            return []
        result = self.list_hotspots(filters=GitHubHotspotFilters(query=normalized), limit=limit)
        return result.rows

    def resolve_report_path(self) -> Path | None:
        if self.report_path:
            if self.report_path.is_dir():
                candidate = self.report_path / HOTLIST_FILENAME
                return candidate if candidate.exists() else None
            return self.report_path if self.report_path.exists() else None
        if not self.output_root.exists():
            return None

        matches = [path for path in self.output_root.glob(f"**/{HOTLIST_FILENAME}") if path.is_file()]
        if not matches:
            return None
        return max(matches, key=lambda path: path.stat().st_mtime)

    def _read_rows(self, report_path: Path) -> list[GitHubHotspotRow]:
        rows: list[GitHubHotspotRow] = []
        for raw_line in report_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line:
                continue
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            row = _row_from_payload(payload)
            if row is not None:
                rows.append(row)
        return rows

    def _stats(self, rows: list[GitHubHotspotRow], report_path: Path | None) -> GitHubHotspotStats:
        updated_at = None
        if report_path and report_path.exists():
            updated_at = datetime.fromtimestamp(report_path.stat().st_mtime)
        return GitHubHotspotStats(
            total=len(rows),
            strong_count=sum(1 for row in rows if row.level == "S"),
            hot_count=sum(1 for row in rows if row.level == "A"),
            watch_count=sum(1 for row in rows if row.level == "B"),
            risky_count=sum(1 for row in rows if row.is_risky),
            report_path=report_path,
            updated_at=updated_at,
        )


def _row_from_payload(payload: dict[str, Any]) -> GitHubHotspotRow | None:
    profile = payload.get("profile") if isinstance(payload.get("profile"), dict) else {}
    digest = payload.get("digest") if isinstance(payload.get("digest"), dict) else {}
    ranking = payload.get("ranking") if isinstance(payload.get("ranking"), dict) else {}

    repo_full_name = _text(profile.get("repo_full_name")) or _text(digest.get("project_name"))
    if not repo_full_name:
        return None

    return GitHubHotspotRow(
        normalized_item_id=_int_or_none(profile.get("normalized_item_id")),
        raw_item_id=_int_or_none(profile.get("raw_item_id")),
        repo_full_name=repo_full_name,
        url=_text(profile.get("url")),
        homepage=_text(profile.get("homepage")),
        source_id=_text(profile.get("source_id")),
        published_at=_parse_datetime(profile.get("published_at")),
        summary_cn=_text(digest.get("summary_cn")),
        description_cn=_text(digest.get("description_cn")),
        project_type=_text(digest.get("project_type")),
        keywords=_string_list(digest.get("keywords")),
        target_users=_string_list(digest.get("target_users")),
        main_features=_string_list(digest.get("main_features")),
        how_to_try=_text(digest.get("how_to_try")),
        stars=_int(profile.get("stars")),
        forks=_int(profile.get("forks")),
        watchers=_int(profile.get("watchers")),
        open_issues=_int(profile.get("open_issues")),
        primary_language=_text(profile.get("primary_language")),
        license_name=_text(profile.get("license_name")),
        pushed_at=_parse_datetime(profile.get("pushed_at")),
        latest_release_names=_release_names(profile.get("latest_releases")),
        final_score=_int(ranking.get("final_score")),
        level=_text(ranking.get("level")) or "-",
        decision=_text(ranking.get("decision")) or "未分级",
        ai_relevance_score=_int(ranking.get("ai_relevance_score")),
        popularity_score=_int(ranking.get("popularity_score")),
        activity_score=_int(ranking.get("activity_score")),
        quality_score=_int(ranking.get("quality_score")),
        usability_score=_int(ranking.get("usability_score")),
        risk_score=_int(ranking.get("risk_score")),
        rank_reason=_text(ranking.get("rank_reason")),
        risk_flags=_string_list(ranking.get("risk_flags")),
    )


def _matches_filters(row: GitHubHotspotRow, filters: GitHubHotspotFilters) -> bool:
    if filters.query and filters.query.strip().lower() not in _search_text(row):
        return False
    if filters.level and row.level != filters.level:
        return False
    if filters.language and (row.primary_language or "").lower() != filters.language.lower():
        return False
    if filters.project_type and (row.project_type or "") != filters.project_type:
        return False
    if filters.min_score is not None and row.final_score < filters.min_score:
        return False
    if not filters.include_risky and row.is_risky:
        return False
    return True


def _search_text(row: GitHubHotspotRow) -> str:
    values = [
        row.repo_full_name,
        row.summary_cn,
        row.description_cn,
        row.project_type,
        row.primary_language,
        row.license_name,
        row.rank_reason,
        *row.keywords,
        *row.target_users,
        *row.main_features,
        *row.risk_flags,
    ]
    return " ".join(value for value in values if value).lower()


def _release_names(raw: Any) -> list[str]:
    if not isinstance(raw, list):
        return []
    names: list[str] = []
    for item in raw[:3]:
        if not isinstance(item, dict):
            continue
        name = _text(item.get("name")) or _text(item.get("tag_name"))
        if name:
            names.append(name)
    return names


def _string_list(raw: Any) -> list[str]:
    if not isinstance(raw, list):
        return []
    return [str(item) for item in raw if item is not None]


def _text(raw: Any) -> str | None:
    if raw is None:
        return None
    value = str(raw).strip()
    return value or None


def _int(raw: Any) -> int:
    value = _int_or_none(raw)
    return value if value is not None else 0


def _int_or_none(raw: Any) -> int | None:
    if raw is None or raw == "":
        return None
    try:
        return int(raw)
    except (TypeError, ValueError):
        return None


def _parse_datetime(raw: Any) -> datetime | None:
    value = _text(raw)
    if not value:
        return None
    try:
        return date_parser.parse(value)
    except (TypeError, ValueError):
        return None


def _datetime_sort_value(value: datetime | None) -> float:
    if value is None:
        return 0.0
    return value.timestamp()
